### ISSUE TITLE
500 error when slash on the end of "respec"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#474] opened 2017-08-14 03:39 UTC
I'm getting a 500 error "unknown generator: respec/" trying to publish the web manifest spec. The offending URL:
https://labs.w3.org/spec-generator/?type=respec\&url=http%3A%2F%2Fw3c.github.io%2Fmanifest%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dappmanifest

 
It appears that a "/" is getting inserted at the end of the "type" query param  somewhere in the pipeline  (not sure where tho): 
 
https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0045.html

The echidna manifest seems fine:
https://github.com/w3c/manifest/blob/gh-pages/ECHIDNA

And our travis file also seems ok:
https://github.com/w3c/manifest/blob/gh-pages/.travis.yml

Maybe a recent regression?

**Comment by marcoscaceres** [comment] 2017-08-14 03:40
The expected URL should be (no "/" after respec):
https://labs.w3.org/spec-generator/?type=respec&url=http%3A%2F%2Fw3c.github.io%2Fmanifest%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dappmanifest

Document then generates fine.

**Comment by tripu** [comment] 2017-08-25 16:11
@deniak, I thought I had traced this back to [this escaping ampersands in the shell script for sendmail](https://github.com/w3c/echidna/pull/352) (I know those escapes are necessary).

But then I realised that that would affect the resulting e-mail at the end of the pipeline only; while [in the example @marcoscaceres shared](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0045.html), this issue seemed to have caused `retrieve-resources` to fail ([here](https://github.com/w3c/echidna/blob/master/lib/document-downloader.js#L27-L32)), before the sendmail script could be invoked&hellip;

So I'm not sure where this is coming from.

(In any case, this reminds me I have to resume work on #431, which will make away with the sendmail script altogether!)

**Comment by tripu** [comment] 2017-08-28 15:21
After investigating a bit more, it seems that the extraneous backslash on the error e-mail is just a (minor) issue related to escaping characters when passing the message to the sendmail script, at the end of the process&nbsp;&mdash;&nbsp;*not* the cause of that error `500`.

Evidence:

* This problem occurred for `appmanifest` [only twice in a row in a very brief span of time](https://www.w3.org/Search/Mail/Public/advanced_search?keywords=http%3A%2F%2Fw3c.github.io%2Fmanifest%2FECHIDNA&hdr-1-name=subject&hdr-1-query=&hdr-2-name=from&hdr-2-query=&hdr-3-name=message-id&hdr-3-query=&period_month=Aug&period_year=2017&index-grp=Public__FULL&index-type=t&type-index=public-tr-notifications&resultsperpage=20&sortby=date) (Fri Aug 11 02:39:51&ndash;02:42:17 UTC 2017); [all other attempts to publish after that, and all attempts for several months before](https://www.w3.org/Search/Mail/Public/search?type-index=public-tr-notifications&index-type=t&keywords=appmanifest&search=Search), were successful. Neither Echidna nor the `appmanifest` manifest have changed significantly lately. So the error looks like some hiccup in spec-generator or in respec (out-of-memory? process being temporarily down?).
* Original JSON files for the shortname `appmanifest` on our servers look all right in all cases: there is no `\&`; the URIs are right. And those are the URIs being used by Echidna to retrieve the specs.

I'm leaving this issue open and assigned to me. It'll be fixed by #431.

**Comment by marcoscaceres** [comment] 2017-09-01 06:47
Thanks for looking into this, @tripu!

**Comment by tripu** [comment] 2018-11-16 13:05
Doesn't apply after the recent move from a custom Bash script to `nodemailer` (#431).

**Closed by tripu** 2018-11-16 13:05 UTC
Labels: bug
