### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by deniak** [w3c/echidna#577] opened 2018-06-21 08:35 UTC
[jscs has merged with ESLint](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.x0o1xqkk9)

**Comment by tripu** [comment] 2018-06-25 17:28
&hellip;and do the same in all JS projects.

**Comment by tripu** [comment] 2018-07-23 06:07
Duplicate of #215. I'm on it.

**Closed by tripu** 2018-07-23 06:07 UTC
Labels: enhancement
